from leapp.actors import Actor
from leapp.models import NetworkManagerInfo
from leapp.tags import ApplicationsPhaseTag, IPUWorkflowTag


class NetworkManagerUpdateConfig(Actor):
    name = 'network_manager_update_config'
    description = 'This actor updates NetworkManager configuration for RHEL8.'
    consumes = (NetworkManagerInfo,)
    produces = ()
    tags = (ApplicationsPhaseTag, IPUWorkflowTag)

    def process(self):
        path = '/usr/lib/NetworkManager/conf.d/10-dhcp-dhclient.conf'
        for nm_info in self.consume(NetworkManagerInfo):
            self.log.info('Consuming dhcp={}...'.format(nm_info.dhcp))
            if nm_info.dhcp == '':
                try:
                    with open(path, 'w') as f:
                        f.write('# Generated by leapp\n')
                        f.write('[main]\n')
                        f.write('dhcp=dhclient\n')
                        self.log.info('Generated {} configuration snippet'.format(path))
                        return
                except IOError as e:
                    self.log.warning('Write error: {}...'.format(e))
                
